version: 2.1

commands:
  sayhello:
    description: "A very simple command for demonstration purposes"
    parameters:
      to:
        type: string
        default: "World"
    steps:
      - run: 
          echo Hello << parameters.to >>

jobs:
  myjob:
    docker:
      - image: circleci/node:13.8.0

    steps:
      - sayhello: # invoke command "sayhello"
          to: 'Lev'

workflows:
  my_workflow:
    jobs:
      - myjob

